Add empty mutations version field
hasura/ndc-postgres pull request #213
Opened 2023-12-15 16:21 UTC by danieljharvey

### What

### How

2023-12-15 17:37 UTC, plcplc requested changes
Nice, just one important detail about versions.

2023-12-18 10:45 UTC, danieljharvey commented on crates/connectors/ndc-postgres/src/configuration/version1.rs
> +            mutations_version: None,
Sounds good. Is this OK @plcplc ?

2023-12-18 11:07 UTC, plcplc approved these changes

2023-12-18 11:07 UTC, plcplc commented on crates/connectors/ndc-postgres/src/configuration/version1.rs
> +            mutations_version: None,
Splendid.

2023-12-18 11:22 UTC, merged